name: Build

on:
  push:
    branches: ["main", "modernise"]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name:
      Build ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{
      matrix.features.description }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
          - { target: wasm32v1-none, description: Wasm v1 }
        rust:
          - { version: "1.87", description: MSRV, atomics: false }
          - { version: stable, atomics: false }
          - { version: nightly, atomics: false }
          - {
              version: nightly,
              description: with Atomics,
              atomics: true,
              components: rust-src,
              cflags: -matomics -mbulk-memory,
              rustflags: "-Ctarget-feature=+atomics,+bulk-memory",
              build-std: true,
            }
        features:
          - { features: "", description: (`default`) }
          - { features: --features serde, description: "(`default`, `serde`)" }
          - { features: --no-default-features --features std, description: (`std`) }
          - { features: --no-default-features, no_std: true, description: (`no_std`) }
          - {
              features: --no-default-features --features msrv,
              no_std: true,
              description: "(`no_std`, `msrv`)",
            }
          - {
              features: --no-default-features --features serde,
              no_std: true,
              description: "(`no_std`, `serde`)",
            }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              description: "(`no_std`, `msrv`, `serde`)",
            }
        exclude:
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { version: nightly }
          - target: { target: wasm32-unknown-unknown, description: Web }
            rust: { version: nightly, atomics: false }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: "1.87" }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: stable }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            features: { no_std: false }

    uses: ./.github/workflows/rust-ci.yml
    with:
      command: build
      target: ${{ matrix.target.target }}
      toolchain: ${{ matrix.rust.version }}
      features: ${{ matrix.features.features }}
      components: ${{ matrix.rust.components || '' }}
      cflags: ${{ matrix.rust.cflags || '' }}
      rustflags: ${{ matrix.rust.rustflags || '' }}
      build-std: ${{ matrix.rust.build-std || false }}
      no-std: ${{ matrix.features.no_std || false }}

  minimal-versions:
    name:
      Minimal Versions ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{
      matrix.features.description }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tests-crates/minimal-versions

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
          - { target: wasm32v1-none, description: Wasm v1 }
        rust:
          - { version: "1.87", description: MSRV }
          - { version: stable }
          - { version: nightly }
        features:
          - { features: "", description: (`default`) }
          - { features: --features serde, description: "(`default`, `serde`)" }
          - { features: --no-default-features --features std, description: (`std`) }
          - { features: --no-default-features, no_std: true, description: (`no_std`) }
          - {
              features: --no-default-features --features msrv,
              no_std: true,
              description: "(`no_std`, `msrv`)",
            }
          - {
              features: --no-default-features --features serde,
              no_std: true,
              description: "(`no_std`, `serde`)",
            }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              description: "(`no_std`, `msrv`, `serde`)",
            }
        exclude:
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { version: nightly }
          - target: { target: wasm32-unknown-unknown, description: Web }
            rust: { version: nightly }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: "1.87" }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: stable }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            features: { no_std: false }

    steps:
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.rust.version }}
          target: ${{ matrix.target.target }}
      - name: Downgrade to minimal versions
        run: |
          rustup toolchain install nightly --profile minimal
          cargo +nightly update -Z minimal-versions
      - name: Build
        run: cargo build ${{ matrix.features.features }} --target ${{ matrix.target.target }}

  resolver:
    name: |
      `resolver = "3"` ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{ matrix.features.description }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tests-crates/resolver

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
          - { target: wasm32v1-none, description: Wasm v1 }
        rust:
          - { version: "1.87", description: MSRV }
          - { version: stable }
          - { version: nightly }
        features:
          - { features: "", description: (`default`) }
          - { features: --features serde, description: "(`default`, `serde`)" }
          - { features: --no-default-features --features std, description: (`std`) }
          - { features: --no-default-features, no_std: true, description: (`no_std`) }
          - {
              features: --no-default-features --features msrv,
              no_std: true,
              description: "(`no_std`, `msrv`)",
            }
          - {
              features: --no-default-features --features serde,
              no_std: true,
              description: "(`no_std`, `serde`)",
            }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              description: "(`no_std`, `msrv`, `serde`)",
            }
        exclude:
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { version: nightly }
          - target: { target: wasm32-unknown-unknown, description: Web }
            rust: { version: nightly }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: "1.87" }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: stable }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            features: { no_std: false }

    steps:
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.rust.version }}
          target: ${{ matrix.target.target }}
      - name: Build
        run: cargo build ${{ matrix.features.features }} --target ${{ matrix.target.target }}

  docsrs-error:
    name: |
      `cfg(docsrs)` error message ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{ matrix.features.description }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
          - { target: wasm32v1-none, description: Wasm v1 }
        rust:
          - { version: "1.87", description: MSRV }
          - { version: stable }
          - { version: nightly }
        # We don't check `serde` because it fails on the dependency itself already.
        features:
          - { features: "", no_std: false }
          - { features: --no-default-features, no_std: true, description: (`no_std`) }
        exclude:
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { version: nightly }
          - target: { target: wasm32-unknown-unknown, description: Web }
            rust: { version: nightly }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: "1.87" }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            rust: { version: stable }
          - target: { target: wasm32v1-none, description: Wasm v1 }
            features: { no_std: false }

    steps:
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ matrix.rust.version }}
          target: ${{ matrix.target.target }}
      - name: Build
        env:
          RUSTFLAGS: --cfg docsrs
        run:
          diff <(cargo build --target ${{ matrix.target.target }} ${{ matrix.features.features }}
          --message-format json | jq -r "select(.reason == \"compiler-message\") |
          .message.message") .github/docsrs-error-${{ matrix.rust.version }}.txt
