name: Format

on:
  push:
    branches: ["main", "modernise"]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  rustfmt:
    name: Rustfmt

    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: rustfmt
      - name: Run Rustfmt
        run: cargo fmt --check

  taplo:
    name: Taplo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Taplo
        uses: ./.github/actions/setup-tool
        with:
          tool: taplo-cli
      - name: Run Taplo
        run: taplo fmt --check

  prettier:
    name: Prettier

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Prettier
        run: sudo npm i -g prettier
      - name: Run Prettier
        run: prettier . --check
