name: Lint

on:
  push:
    branches: ["main", "modernise"]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  clippy:
    name:
      Clippy ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{
      matrix.features.description }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
        rust:
          - { version: stable, atomics: false }
          - { version: nightly, atomics: false }
          - {
              version: nightly,
              description: with Atomics,
              atomics: true,
              components: rust-src,
              cflags: -matomics -mbulk-memory,
              rustflags: "-Ctarget-feature=+atomics,+bulk-memory",
              build-std: true,
            }
        features:
          - { features: "", native: true, description: (`default`) }
          - { features: --features serde, native: false, description: (`default` `serde`) }
          - { features: --no-default-features --features std, native: false, description: (`std`) }
          - { features: --no-default-features, no_std: true, native: true, description: (`no_std`) }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              description: "(`no_std`, `msrv`, `serde`)",
            }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              nightly: true,
              description: "Nightly (`no_std`, `msrv`, `serde`)",
            }
        exclude:
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { atomics: true }
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            features: { native: false }
          - rust: { version: nightly, atomics: false }
            features: { nightly: false }
          - features: { nightly: true }
            rust: { version: stable }
          - rust: { atomics: true }
            features: { nightly: true }

    uses: ./.github/workflows/rust-ci.yml
    with:
      command: clippy
      target: ${{ matrix.target.target }}
      toolchain: ${{ matrix.rust.version }}
      features: ${{ matrix.features.features }}
      components: clippy,${{ matrix.rust.components || '' }}
      cflags: ${{ matrix.rust.cflags || '' }}
      rustflags: ${{ matrix.rust.rustflags || '' }}
      build-std: ${{ matrix.rust.build-std || false }}
      no-std: ${{ matrix.features.no_std || false }}

  rustdoc:
    name:
      Rustdoc ${{ matrix.target.description }} ${{ matrix.rust.description }} ${{
      matrix.features.description }} ${{ matrix.docsrs.description }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - { target: x86_64-unknown-linux-gnu, description: Native }
          - { target: wasm32-unknown-unknown, description: Web }
        rust:
          - { version: stable, atomics: false }
          - { version: nightly, atomics: false }
          - {
              version: nightly,
              description: with Atomics,
              atomics: true,
              components: rust-src,
              cflags: -matomics -mbulk-memory,
              rustflags: "-Ctarget-feature=+atomics,+bulk-memory",
              build-std: true,
            }
        features:
          - { features: "", native: true, description: (`default`) }
          - { features: --features serde, description: (`default` `serde`) }
          - { features: --no-default-features --features std, description: (`std`) }
          - { features: --no-default-features, no_std: true, native: true, description: (`no_std`) }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              description: "(`no_std`, `msrv`, `serde`)",
            }
          - {
              features: "--no-default-features --features msrv,serde",
              no_std: true,
              nightly: true,
              description: "Nightly (`no_std`, `msrv`, `serde`)",
            }
        docsrs:
          - { flags: "", nightly: false }
          - { description: (docs.rs), flags: --cfg=docsrs, nightly: true }
        exclude:
          - docsrs: { flags: "", nightly: false }
            rust: { version: nightly, atomics: false }
            features: { nightly: false }
          - docsrs: { flags: --cfg=docsrs, nightly: true }
            rust: { version: stable }
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            rust: { atomics: true }
          - target: { target: x86_64-unknown-linux-gnu, description: Native }
            features: { native: false }
          - features: { nightly: true }
            rust: { version: stable }
          - rust: { atomics: true }
            features: { nightly: true }

    uses: ./.github/workflows/rust-ci.yml
    with:
      command: doc
      target: ${{ matrix.target.target }}
      toolchain: ${{ matrix.rust.version }}
      features: ${{ matrix.features.features }}
      components: ${{ matrix.rust.components || '' }}
      cflags: ${{ matrix.rust.cflags || '' }}
      rustflags: ${{ matrix.rust.rustflags || '' }}
      build-std: ${{ matrix.rust.build-std || false }}
      no-std: ${{ matrix.features.no_std || false }}
      extra-args: ${{ matrix.docsrs.flags != '' && '--cfg=docsrs' || '' }}
      rustdocflags: -D warnings ${{ matrix.rust.rustflags || '' }} ${{ matrix.docsrs.flags }}

  file-permissions:
    name: File Permissions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List all files that are executable
        run: find -type f -executable ! -path './.git/*'
      - name: Fail if any executable files were found
        run: find -type f -executable ! -path './.git/*' -exec false {} +
