name: Publish

on:
  push:
    branches: ["main", "modernise"]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: stable
      - name: Test Publish
        run: cargo publish --dry-run
